// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class Cache
{
    public string Key { get; set; }

    public string Value { get; set; }

    public int Expiration { get; set; }
}