// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class Car
{
    public ulong Id { get; set; }

    public ulong MarkId { get; set; }

    public ulong ModelId { get; set; }

    public ulong CountryId { get; set; }

    public ulong TypeId { get; set; }

    public ulong ColorId { get; set; }

    /// <summary>
    /// VIN
    /// </summary>
    public string Vin { get; set; }

    /// <summary>
    /// PTS
    /// </summary>
    public string Pts { get; set; }

    /// <summary>
    /// дата производства
    /// </summary>
    public DateOnly DateAt { get; set; }

    /// <summary>
    /// цена
    /// </summary>
    public decimal Price { get; set; }

    /// <summary>
    /// блок
    /// </summary>
    public ulong Block { get; set; }

    public DateTime? DeletedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CarPhoto> CarPhotos { get; set; } = new List<CarPhoto>();

    public virtual CarColor Color { get; set; }

    public virtual CarCountry Country { get; set; }

    public virtual CarMark Mark { get; set; }

    public virtual CarModel Model { get; set; }

    public virtual ICollection<OrderCar> OrderCars { get; set; } = new List<OrderCar>();

    public virtual CarType Type { get; set; }
}