// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class CarMarkModelCountry
{
    public ulong Id { get; set; }

    public ulong MarkId { get; set; }

    public ulong ModelId { get; set; }

    public ulong CountryId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual CarCountry Country { get; set; }

    public virtual CarMark Mark { get; set; }

    public virtual CarModel Model { get; set; }
}