// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class Client
{
    public ulong Id { get; set; }

    public string ClientName { get; set; }

    public string ClientMail { get; set; }

    public string ClientPhone { get; set; }

    public string ClientAddress { get; set; }

    public string ClientAddData { get; set; }

    public bool ClientStatus { get; set; }

    public DateTime? DeletedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}