// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class FailedJob
{
    public ulong Id { get; set; }

    public string Uuid { get; set; }

    public string Connection { get; set; }

    public string Queue { get; set; }

    public string Payload { get; set; }

    public string Exception { get; set; }

    public DateTime FailedAt { get; set; }
}