// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class Job
{
    public ulong Id { get; set; }

    public string Queue { get; set; }

    public string Payload { get; set; }

    public byte Attempts { get; set; }

    public uint? ReservedAt { get; set; }

    public uint AvailableAt { get; set; }

    public uint CreatedAt { get; set; }
}