// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class JobBatch
{
    public string Id { get; set; }

    public string Name { get; set; }

    public int TotalJobs { get; set; }

    public int PendingJobs { get; set; }

    public int FailedJobs { get; set; }

    public string FailedJobIds { get; set; }

    public string Options { get; set; }

    public int? CancelledAt { get; set; }

    public int CreatedAt { get; set; }

    public int? FinishedAt { get; set; }
}