// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class Migration
{
    public uint Id { get; set; }

    public string Migration1 { get; set; }

    public int Batch { get; set; }
}