// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class Order
{
    public ulong Id { get; set; }

    public ulong ClientId { get; set; }

    public ulong UserId { get; set; }

    public ulong PaymentId { get; set; }

    public ulong DeliveryId { get; set; }

    public string DeliveryAddress { get; set; }

    public DateTime? DeletedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Client Client { get; set; }

    public virtual Delivery Delivery { get; set; }

    public virtual ICollection<OrderCar> OrderCars { get; set; } = new List<OrderCar>();

    public virtual ICollection<OrderStatus> OrderStatuses { get; set; } = new List<OrderStatus>();

    public virtual Payment Payment { get; set; }

    public virtual User User { get; set; }
}