// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class PersonalAccessToken
{
    public ulong Id { get; set; }

    public string TokenableType { get; set; }

    public ulong TokenableId { get; set; }

    public string Name { get; set; }

    public string Token { get; set; }

    public string Abilities { get; set; }

    public DateTime? LastUsedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }
}