// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class Session
{
    public string Id { get; set; }

    public ulong? UserId { get; set; }

    public string IpAddress { get; set; }

    public string UserAgent { get; set; }

    public string Payload { get; set; }

    public int LastActivity { get; set; }
}