// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class UserDepartmentPosition
{
    public ulong Id { get; set; }

    public ulong DepartmentId { get; set; }

    public ulong PositionId { get; set; }

    public DateTime? DeletedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual UserDepartment Department { get; set; }

    public virtual UserPosition Position { get; set; }
}