// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class User
{
    public ulong Id { get; set; }

    /// <summary>
    /// логин
    /// </summary>
    public string Login { get; set; }

    /// <summary>
    /// пароль
    /// </summary>
    public string Password { get; set; }

    /// <summary>
    /// имя
    /// </summary>
    public string Firstname { get; set; }

    /// <summary>
    /// фамилия
    /// </summary>
    public string Surname { get; set; }

    /// <summary>
    /// отчество
    /// </summary>
    public string Patronymic { get; set; }

    /// <summary>
    /// email
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// телефон
    /// </summary>
    public string Phone { get; set; }

    /// <summary>
    /// день рождения
    /// </summary>
    public DateOnly? Birthday { get; set; }

    /// <summary>
    /// отдел
    /// </summary>
    public ulong? DepartmentId { get; set; }

    /// <summary>
    /// должность
    /// </summary>
    public ulong? PositionId { get; set; }

    /// <summary>
    /// трудоустройство
    /// </summary>
    public DateOnly? StartWork { get; set; }

    /// <summary>
    /// статус
    /// </summary>
    public ulong? StatusId { get; set; }

    /// <summary>
    /// смена статуса
    /// </summary>
    public DateOnly? StatusAt { get; set; }

    /// <summary>
    /// разрешения
    /// </summary>
    public string Permissions { get; set; }

    public DateTime? DeletedAt { get; set; }

    public string RememberToken { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual UserDepartment Department { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual UserPosition Position { get; set; }

    public virtual UserStatus Status { get; set; }
}