// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Project.Models;

public partial class UserDepartment
{
    public ulong Id { get; set; }

    public string DepartmentName { get; set; }

    public string DepartmentDescription { get; set; }

    public string DepartmentMail { get; set; }

    public DateTime? DeletedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<UserDepartmentPosition> UserDepartmentPositions { get; set; } = new List<UserDepartmentPosition>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}